services:
  customankimaps:
    image: ghcr.io/beclay-vps/customankimaps:latest
    container_name: customankimaps
    restart: always
    environment:
      - PORT=8000
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.customankimaps.rule=Host(`custommaps.beclay.fr`)"
      - "traefik.http.routers.customankimaps.entrypoints=websecure"
      - "traefik.http.routers.customankimaps.tls.certresolver=le"
      - "traefik.http.services.customankimaps.loadbalancer.server.port=8000"

networks:
  web:
    external: true